# Generated by Django 6.0.1 on 2026-08-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_post_comment_postfavorite_postlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="story_file",
            field=models.FileField(
                blank=True, null=True, upload_to="character/stories/"
            ),
        ),
    ]
